### ISSUE TITLE
about the order of the mean value of images/pixels

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [sanghoon/pva-faster-rcnn#14]
hi @sanghoon what the order of mean value of images/pixels. for example, for py-faster-rcnn, the order is BGR, what about the order of pvanet and the imagenet model? thanks.

**Comment by rajiv235** [comment]
Hi @sanghoon , I tried retraining pvanet-faster rcnn on my custom dataset and it works well except for ir images(or gray scaled images). What means would you recommend for this case?
Thanks

**Comment by sanghoon** [comment]
Hi @zimenglan-sysu-512,
I just used fixed mean values computed by my former colleague,
but I'm quite sure it's the same order with py-faster-rcnn.

@rajiv235 
I'm afraid that I can't give you some comments on that since we haven't tried running our networks on IR or grayscaled images.
I'd appreciate it if you could share your experience about it.
